/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { BranchMetadata } from "./branchmetadata";
import { Expose, Type } from "class-transformer";

export class BranchInfo extends SpeakeasyBase {
    /**
     * Branch name
     */
    @SpeakeasyMetadata()
    @Expose({ name: "branch" })
    branch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => BranchMetadata)
    metadata?: BranchMetadata;
}
