/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * OK
 */
export class CreateByIdResponse extends SpeakeasyBase {
    /**
     * Returns the id of the created document.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;
}
