/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class GetSetRequest extends SpeakeasyBase {
  /**
   * free form byte[] value
   */
  @SpeakeasyMetadata()
  @Expose({ name: "value" })
  value?: string;
}
