/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * OK
 */
export class HealthCheckResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "response" })
  response?: string;
}
