import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ImportRequestOptions } from "./importrequestoptions";
import { Expose, Type } from "class-transformer";

export class ImportRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "autogenerated" })
  autogenerated?: string[];

  @SpeakeasyMetadata()
  @Expose({ name: "branch" })
  branch?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "create_collection" })
  createCollection?: boolean;

  @SpeakeasyMetadata()
  @Expose({ name: "documents" })
  documents?: Record<string, any>[];

  @SpeakeasyMetadata()
  @Expose({ name: "options" })
  @Type(() => ImportRequestOptions)
  options?: ImportRequestOptions;

  @SpeakeasyMetadata()
  @Expose({ name: "primary_key" })
  primaryKey?: string[];
}
