/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { WriteOptions } from "./writeoptions";
import { Expose, Type } from "class-transformer";

/**
 * additional options for import requests.
 */
export class ImportRequestOptions extends SpeakeasyBase {
    /**
     * Additional options to modify write requests.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "write_options" })
    @Type(() => WriteOptions)
    writeOptions?: WriteOptions;
}
