/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ResponseMetadata } from "./responsemetadata";
import { Expose, Type } from "class-transformer";

export class InsertResponse extends SpeakeasyBase {
    /**
     * an array returns the value of the primary keys.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "keys" })
    keys?: string[];

    /**
     * Has metadata related to the documents stored.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => ResponseMetadata)
    metadata?: ResponseMetadata;

    /**
     * An enum with value set as "inserted"
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}
