/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class InsertNamespaceMetadataResponseValue extends SpeakeasyBase {}

/**
 * Insertion of namespace metadata response
 */
export class InsertNamespaceMetadataResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadataKey" })
    metadataKey?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "namespaceId" })
    namespaceId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    @Type(() => InsertNamespaceMetadataResponseValue)
    value?: InsertNamespaceMetadataResponseValue;
}
