/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class InsertNamespaceMetadataRequestValue extends SpeakeasyBase {}

/**
 * Request insertion of namespace metadata
 */
export class InsertNamespaceMetadataRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadataKey" })
    metadataKey?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    @Type(() => InsertNamespaceMetadataRequestValue)
    value?: InsertNamespaceMetadataRequestValue;
}
