/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NamespaceInfo } from "./namespaceinfo";
import { Expose, Type } from "class-transformer";

export class ListNamespacesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: NamespaceInfo })
    @Expose({ name: "namespaces" })
    @Type(() => NamespaceInfo)
    namespaces?: NamespaceInfo[];
}
