/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * Request current namespace quota limits
 */
export class QuotaLimitsRequest extends SpeakeasyBase {}
