/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * Request current namespace quota usage
 */
export class QuotaUsageRequest extends SpeakeasyBase {}
