/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ReadRequestOptions } from "./readrequestoptions";
import { Expose, Type } from "class-transformer";

/**
 * To read specific fields from a document. Default is all.
 */
export class Fields extends SpeakeasyBase {}

/**
 * Returns documents matching this filter. A filter can simply be a key, value pair where a key is the field name and the value would be the value for this field. Tigris also allows complex filtering by passing logical expressions. Logical filters are applied on two or more fields using `$or` and `$and`. A few examples of filters: <li> To read a user document where the id has a value 1: ```{"id": 1 }``` <li> To read all the user documents where the key "id" has a value 1 or 2 or 3: `{"$or": [{"id": 1}, {"id": 2}, {"id": 3}]}` Filter allows setting collation on an individual field level. To set collation for all the fields see options. The detailed documentation of the filter is <a href="https://docs.tigrisdata.com/overview/query#specification-1" title="here">here</a>.
 */
export class ReadRequestFilter extends SpeakeasyBase {}

export class ReadRequest extends SpeakeasyBase {
    /**
     * Optionally specify a database branch name to perform operation on
     */
    @SpeakeasyMetadata()
    @Expose({ name: "branch" })
    branch?: string;

    /**
     * To read specific fields from a document. Default is all.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "fields" })
    @Type(() => Fields)
    fields?: Fields;

    /**
     * Returns documents matching this filter. A filter can simply be a key, value pair where a key is the field name and the value would be the value for this field. Tigris also allows complex filtering by passing logical expressions. Logical filters are applied on two or more fields using `$or` and `$and`. A few examples of filters: <li> To read a user document where the id has a value 1: ```{"id": 1 }``` <li> To read all the user documents where the key "id" has a value 1 or 2 or 3: `{"$or": [{"id": 1}, {"id": 2}, {"id": 3}]}` Filter allows setting collation on an individual field level. To set collation for all the fields see options. The detailed documentation of the filter is <a href="https://docs.tigrisdata.com/overview/query#specification-1" title="here">here</a>.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "filter" })
    @Type(() => ReadRequestFilter)
    filter?: ReadRequestFilter;

    /**
     * Options that can be used to modify the results, for example "limit" to control the number of documents returned by the server.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "options" })
    @Type(() => ReadRequestOptions)
    options?: ReadRequestOptions;

    /**
     * Array of fields and corresponding sort orders to order the results. Ex: 1 `[{ "salary": "$desc" }]`, Ex: 2  `[{ "salary": "$asc"}]`
     */
    @SpeakeasyMetadata()
    @Expose({ name: "sort" })
    sort?: string;
}
