/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Message } from "./message";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ReadMessagesResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "message" })
    @Type(() => Message)
    message?: Message;
}
