/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ResponseMetadata } from "./responsemetadata";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class ReplaceResponse extends SpeakeasyBase {
  /**
   * an array returns the value of the primary keys.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "keys" })
  keys?: string[];

  /**
   * Has metadata related to the documents stored.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => ResponseMetadata)
  metadata?: ResponseMetadata;

  /**
   * an enum with value set as "replaced"
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status?: string;
}
