/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Additional options for replace requests.
 */
export class ReplaceRequestOptions extends SpeakeasyBase {
    /**
     * Additional options to modify write requests.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "write_options" })
    writeOptions?: Record<string, any>;
}
