/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Rollback transaction with the given ID
 */
export class RollbackTransactionRequest extends SpeakeasyBase {
  /**
   * Optionally specify a database branch name to perform operation on
   */
  @SpeakeasyMetadata()
  @Expose({ name: "branch" })
  branch?: string;
}
