/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AppKey } from "./appkey";
import { Expose, Type } from "class-transformer";

/**
 * RotateAppKeyResponse returns the new app key with rotated secret
 */
export class RotateAppKeyResponse extends SpeakeasyBase {
    /**
     * An user AppKey
     */
    @SpeakeasyMetadata()
    @Expose({ name: "app_key" })
    @Type(() => AppKey)
    appKey?: AppKey;
}
