/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * Options that can be used to modify the transaction semantics.
 */
export class TransactionOptions extends SpeakeasyBase {}
