/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UpdateUserMetadataRequestValue extends SpeakeasyBase {}

/**
 * Request update of user metadata
 */
export class UpdateUserMetadataRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadataKey" })
    metadataKey?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    @Type(() => UpdateUserMetadataRequestValue)
    value?: UpdateUserMetadataRequestValue;
}
