/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UpdateUserMetadataResponseValue extends SpeakeasyBase {}

/**
 * Update of user metadata response
 */
export class UpdateUserMetadataResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadataKey" })
    metadataKey?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "namespaceId" })
    namespaceId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "userId" })
    userId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    @Type(() => UpdateUserMetadataResponseValue)
    value?: UpdateUserMetadataResponseValue;
}
