/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { ResponseMetadata } from "./responsemetadata";
import { Expose, Type } from "class-transformer";

/**
 * OK
 */
export class UpdateResponse extends SpeakeasyBase {
    /**
     * Has metadata related to the documents stored.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => ResponseMetadata)
    metadata?: ResponseMetadata;

    /**
     * Returns the number of documents modified.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "modified_count" })
    modifiedCount?: number;

    /**
     * an enum with value set as "updated".
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}
