/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase } from "../../../internal/utils";

/**
 * Additional options to modify write requests.
 */
export class WriteOptions extends SpeakeasyBase {}
