/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class TigrisRotateAppKeySecretPathParams extends SpeakeasyBase {
  /**
   * project name
   */
  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=project",
  })
  project: string;
}

export class TigrisRotateAppKeySecretRequest extends SpeakeasyBase {
  @SpeakeasyMetadata()
  pathParams: TigrisRotateAppKeySecretPathParams;

  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  request: shared.RotateAppKeyRequest;
}

export class TigrisRotateAppKeySecretResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  /**
   * OK
   */
  @SpeakeasyMetadata()
  rotateAppKeyResponse?: shared.RotateAppKeyResponse;

  /**
   * Default error response
   */
  @SpeakeasyMetadata()
  status?: shared.Status;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;
}
